# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2139edf2a0a5be35322688ee26fbe37e24e0bff9dc884854562586c7601a42630a622d994c9879f5e8e74775fb96cf2719076b9bbd47a3cdef229c101dabe0fc

test:
  secret_key_base: aa7cacc038b66611fdca2e7e0a5670524f6b4b4c4fe0b50b6f6d0c54caa8b88915af981b62ef3c2795135c5c83396d64bfac49cb660530802bff8b538ee3ef49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
